import { useEffect, useMemo, useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { getStudents, setOfficeStatus } from "../services/clearanceService";
import useDebounce from "../hooks/useDebounce";
import StatusBadge from "../components/StatusBadge";
import ConfirmationModal from "../components/ConfirmationModal";
import LoadingSpinner from "../components/LoadingSpinner";
import Toast from "../components/Toast";
const currentSession = () => JSON.parse(localStorage.getItem("clearanceSession") || "null");
export default function StaffDashboard() {
  const navigate = useNavigate(), user = currentSession(); const [students, setStudents] = useState({}); const [query, setQuery] = useState(""); const debounced = useDebounce(query, 300); const [match, setMatch] = useState(null); const [pending, setPending] = useState(null); const [saving, setSaving] = useState(false); const [scanner, setScanner] = useState(false); const [token, setToken] = useState(""); const [toast, setToast] = useState(null);
  const load = () => getStudents().then(setStudents).catch(() => setToast({ type: "error", text: "Could not load students." }));
  useEffect(() => { load(); const timer = setInterval(load, 30000); return () => clearInterval(timer); }, []);
  useEffect(() => { const value = debounced.trim().toLowerCase(); if (!value) return setMatch(null); const item = Object.entries(students).find(([id, student]) => id.toLowerCase().includes(value) || student.email?.toLowerCase().includes(value)); setMatch(item ? { studentId: item[0], ...item[1] } : "none"); }, [debounced, students]);
  useEffect(() => { if (!scanner) return; const escape = (e) => e.key === "Escape" && setScanner(false); window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape); }, [scanner]);
  const list = useMemo(() => Object.entries(students), [students]);
  if (!user || user.role !== "staff") return <Navigate to="/login" replace />;
  const confirm = async () => { if (!pending) return; setSaving(true); try { await setOfficeStatus(pending.id, user.office, pending.status, user.office); await load(); setToast({ type: "success", text: `${pending.student.name} marked ${pending.status}.` }); setPending(null); } catch { setToast({ type: "error", text: "Could not save clearance status." }); } finally { setSaving(false); } };
  const scanSubmit = (event) => { event.preventDefault(); if (token.trim()) navigate(`/verify/${token.trim()}`); };
  return <main className="dashboard"><header className="topbar"><div><span className="brand">TLC Clearance</span><p>Welcome, {user.name} · {user.office} office</p></div><button className="button secondary" onClick={() => { localStorage.removeItem("clearanceSession"); navigate("/login"); }}>Logout</button></header><div className="staff-grid"><section className="card wide"><h1>Student requests</h1><p>Review {user.office} clearance requests.</p><div className="request-list" onClick={(event) => { const button = event.target.closest("button[data-id]"); if (button) { const student = students[button.dataset.id]; setPending({ id: button.dataset.id, status: button.dataset.status, student }); } }}>{list.map(([id, student]) => <article className="request-row" key={id}><div><h2>{student.name}</h2><p>{id} · {student.course}</p></div><StatusBadge status={student.clearanceStatus?.[user.office] || "pending"} /><div className="actions"><button className="button approve" data-id={id} data-status="approved">Approve</button><button className="button reject" data-id={id} data-status="rejected">Reject</button></div></article>)}</div></section><aside className="dashboard-side"><section className="card"><h2>Manual student search</h2><label htmlFor="student-search">ID or email</label><input id="student-search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search after 300 ms" />{match === "none" && <p>No student found.</p>}{match && match !== "none" && <div className="match"><strong>{match.name}</strong><p>{match.studentId} · {match.course}</p>{Object.entries(match.clearanceStatus || {}).map(([office, status]) => <p key={office}>{office}: <StatusBadge status={status} /></p>)}</div>}</section><section className="card"><h2>QR scanner</h2><button className="button primary" onClick={() => setScanner(true)}>Scan QR Code</button><button className="button link-button" onClick={() => setScanner(true)}>Or enter code manually</button></section></aside></div>{scanner && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="scan-title"><h2 id="scan-title">Scan QR Code</h2><p>Camera scanning is unavailable here. Paste or enter the token from the QR link.</p><form onSubmit={scanSubmit}><label htmlFor="manual-token">QR token</label><input id="manual-token" autoFocus value={token} onChange={(e) => setToken(e.target.value)} required /><div className="actions"><button type="button" className="button secondary" onClick={() => setScanner(false)}>Close</button><button type="submit" className="button primary">Verify code</button></div></form></section></div>}<ConfirmationModal open={Boolean(pending)} title="Confirm clearance update" message={pending ? `${pending.status === "approved" ? "Approve" : "Reject"} ${pending.student.name}'s ${user.office} clearance?` : ""} onClose={() => setPending(null)} onConfirm={confirm} loading={saving} /><Toast message={toast} /></main>;
}
