import { useCallback, useEffect, useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { getStudent, resolveToken, setOfficeStatus, watchStudents } from "../services/clearanceService";
import StudentRequestList from "../components/StudentRequestList";
import ConfirmationModal from "../components/ConfirmationModal";
import ManualSearch from "../components/ManualSearch";
import QRScanner from "../components/QRScanner";
import Toast from "../components/Toast";

const currentSession = () => JSON.parse(localStorage.getItem("clearanceSession") || "null");
export default function StaffDashboard() {
  const navigate = useNavigate(); const user = currentSession();
  const [students, setStudents] = useState(null), [pendingAction, setPendingAction] = useState(null), [saving, setSaving] = useState(false);
  const [scannerOpen, setScannerOpen] = useState(false), [scanning, setScanning] = useState(false), [searchResult, setSearchResult] = useState(null), [searching, setSearching] = useState(false), [searchError, setSearchError] = useState(""), [toast, setToast] = useState(null);
  useEffect(() => { const unsubscribe = watchStudents(setStudents, () => setToast({ type: "error", text: "Could not receive student updates." })); return unsubscribe; }, []);
  const searchById = useCallback(async (studentId) => { setSearching(true); setSearchError(""); try { const student = await getStudent(studentId); if (!student) { setSearchResult(null); setSearchError("No student was found for that ID."); } else setSearchResult({ studentId, ...student, office: user?.office }); } catch { setSearchError("Unable to look up this student."); } finally { setSearching(false); } }, [user?.office]);
  const confirmAction = async () => { if (!pendingAction) return; setSaving(true); try { await setOfficeStatus(pendingAction.studentId, user.office, pendingAction.status, user.office); setToast({ type: "success", text: `${pendingAction.student.name} marked ${pendingAction.status}.` }); setPendingAction(null); } catch { setToast({ type: "error", text: "Could not save clearance status." }); } finally { setSaving(false); } };
  const handleScan = useCallback(async (token) => { setScanning(true); try { const result = await resolveToken(token, user?.office); if (!result.ok) { const errors = { used: "This QR code has already been used.", expired: "This QR code has expired.", student_missing: "The student linked to this QR code no longer exists." }; throw new Error(errors[result.reason] || "The QR code is invalid."); } setSearchResult({ studentId: result.studentId, ...result.student, office: user?.office }); setScannerOpen(false); setToast({ type: "success", text: `QR code used for ${result.student.name}.` }); } catch (error) { setToast({ type: "error", text: error.message || "Could not read QR code." }); } finally { setScanning(false); } }, [user?.office]);
  if (!user || user.role !== "staff") return <Navigate to="/login" replace />;
  return <main className="dashboard"><header className="topbar"><div><span className="brand">TLC Clearance</span><p>Welcome, {user.name} · {user.office} office</p></div><button className="button secondary" onClick={() => { localStorage.removeItem("clearanceSession"); navigate("/login"); }}>Logout</button></header><div className="staff-grid"><section className="card wide"><h1>Student requests</h1><p>Pending requests for the {user.office} office update automatically.</p><StudentRequestList students={students} office={user.office} onAction={setPendingAction} /></section><aside className="dashboard-side"><ManualSearch onSearch={searchById} result={searchResult} loading={searching} error={searchError} /><section className="card"><h2>QR scanner</h2><p>Scan a student’s time-limited clearance QR code.</p><button className="button primary" type="button" onClick={() => setScannerOpen(true)}>Scan QR Code</button></section></aside></div><QRScanner open={scannerOpen} onClose={() => setScannerOpen(false)} onScan={handleScan} loading={scanning} /><ConfirmationModal open={Boolean(pendingAction)} title="Confirm clearance update" message={pendingAction ? `${pendingAction.status === "approved" ? "Approve" : "Reject"} ${pendingAction.student.name}'s ${user.office} clearance?` : ""} onClose={() => setPendingAction(null)} onConfirm={confirmAction} loading={saving} /><Toast message={toast} /></main>;
}
