<<<<<<< HEAD
import { useCallback, useEffect, useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { getStudent, resolveToken, setOfficeStatus, watchStudents } from "../services/clearanceService";
import StudentRequestList from "../components/StudentRequestList";
import ConfirmationModal from "../components/ConfirmationModal";
import ManualSearch from "../components/ManualSearch";
import QRScanner from "../components/QRScanner";
import Toast from "../components/Toast";

const currentSession = () => JSON.parse(localStorage.getItem("clearanceSession") || "null");
export default function StaffDashboard() {
  const navigate = useNavigate(); const user = currentSession();
  const [students, setStudents] = useState(null), [pendingAction, setPendingAction] = useState(null), [saving, setSaving] = useState(false);
  const [scannerOpen, setScannerOpen] = useState(false), [scanning, setScanning] = useState(false), [searchResult, setSearchResult] = useState(null), [searching, setSearching] = useState(false), [searchError, setSearchError] = useState(""), [toast, setToast] = useState(null);
  useEffect(() => { const unsubscribe = watchStudents(setStudents, () => setToast({ type: "error", text: "Could not receive student updates." })); return unsubscribe; }, []);
  const searchById = useCallback(async (studentId) => { setSearching(true); setSearchError(""); try { const student = await getStudent(studentId); if (!student) { setSearchResult(null); setSearchError("No student was found for that ID."); } else setSearchResult({ studentId, ...student, office: user?.office }); } catch { setSearchError("Unable to look up this student."); } finally { setSearching(false); } }, [user?.office]);
  const confirmAction = async () => { if (!pendingAction) return; setSaving(true); try { await setOfficeStatus(pendingAction.studentId, user.office, pendingAction.status, user.office); setToast({ type: "success", text: `${pendingAction.student.name} marked ${pendingAction.status}.` }); setPendingAction(null); } catch { setToast({ type: "error", text: "Could not save clearance status." }); } finally { setSaving(false); } };
  const handleScan = useCallback(async (token) => { setScanning(true); try { const result = await resolveToken(token, user?.office); if (!result.ok) { const errors = { used: "This QR code has already been used.", expired: "This QR code has expired.", student_missing: "The student linked to this QR code no longer exists." }; throw new Error(errors[result.reason] || "The QR code is invalid."); } setSearchResult({ studentId: result.studentId, ...result.student, office: user?.office }); setScannerOpen(false); setToast({ type: "success", text: `QR code used for ${result.student.name}.` }); } catch (error) { setToast({ type: "error", text: error.message || "Could not read QR code." }); } finally { setScanning(false); } }, [user?.office]);
  if (!user || user.role !== "staff") return <Navigate to="/login" replace />;
  return <main className="dashboard"><header className="topbar"><div><span className="brand">TLC Clearance</span><p>Welcome, {user.name} · {user.office} office</p></div><button className="button secondary" onClick={() => { localStorage.removeItem("clearanceSession"); navigate("/login"); }}>Logout</button></header><div className="staff-grid"><section className="card wide"><h1>Student requests</h1><p>Pending requests for the {user.office} office update automatically.</p><StudentRequestList students={students} office={user.office} onAction={setPendingAction} /></section><aside className="dashboard-side"><ManualSearch onSearch={searchById} result={searchResult} loading={searching} error={searchError} /><section className="card"><h2>QR scanner</h2><p>Scan a student’s time-limited clearance QR code.</p><button className="button primary" type="button" onClick={() => setScannerOpen(true)}>Scan QR Code</button></section></aside></div><QRScanner open={scannerOpen} onClose={() => setScannerOpen(false)} onScan={handleScan} loading={scanning} /><ConfirmationModal open={Boolean(pendingAction)} title="Confirm clearance update" message={pendingAction ? `${pendingAction.status === "approved" ? "Approve" : "Reject"} ${pendingAction.student.name}'s ${user.office} clearance?` : ""} onClose={() => setPendingAction(null)} onConfirm={confirmAction} loading={saving} /><Toast message={toast} /></main>;
=======
import { useEffect, useMemo, useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { getStudents, setOfficeStatus } from "../services/clearanceService";
import useDebounce from "../hooks/useDebounce";
import StatusBadge from "../components/StatusBadge";
import ConfirmationModal from "../components/ConfirmationModal";
import LoadingSpinner from "../components/LoadingSpinner";
import Toast from "../components/Toast";
const currentSession = () => JSON.parse(localStorage.getItem("clearanceSession") || "null");
export default function StaffDashboard() {
  const navigate = useNavigate(), user = currentSession(); const [students, setStudents] = useState({}); const [query, setQuery] = useState(""); const debounced = useDebounce(query, 300); const [match, setMatch] = useState(null); const [pending, setPending] = useState(null); const [saving, setSaving] = useState(false); const [scanner, setScanner] = useState(false); const [token, setToken] = useState(""); const [toast, setToast] = useState(null);
  const load = () => getStudents().then(setStudents).catch(() => setToast({ type: "error", text: "Could not load students." }));
  useEffect(() => { load(); const timer = setInterval(load, 30000); return () => clearInterval(timer); }, []);
  useEffect(() => { const value = debounced.trim().toLowerCase(); if (!value) return setMatch(null); const item = Object.entries(students).find(([id, student]) => id.toLowerCase().includes(value) || student.email?.toLowerCase().includes(value)); setMatch(item ? { studentId: item[0], ...item[1] } : "none"); }, [debounced, students]);
  useEffect(() => { if (!scanner) return; const escape = (e) => e.key === "Escape" && setScanner(false); window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape); }, [scanner]);
  const list = useMemo(() => Object.entries(students), [students]);
  if (!user || user.role !== "staff") return <Navigate to="/login" replace />;
  const confirm = async () => { if (!pending) return; setSaving(true); try { await setOfficeStatus(pending.id, user.office, pending.status, user.office); await load(); setToast({ type: "success", text: `${pending.student.name} marked ${pending.status}.` }); setPending(null); } catch { setToast({ type: "error", text: "Could not save clearance status." }); } finally { setSaving(false); } };
  const scanSubmit = (event) => { event.preventDefault(); if (token.trim()) navigate(`/verify/${token.trim()}`); };
  return <main className="dashboard"><header className="topbar"><div><span className="brand">TLC Clearance</span><p>Welcome, {user.name} · {user.office} office</p></div><button className="button secondary" onClick={() => { localStorage.removeItem("clearanceSession"); navigate("/login"); }}>Logout</button></header><div className="staff-grid"><section className="card wide"><h1>Student requests</h1><p>Review {user.office} clearance requests.</p><div className="request-list" onClick={(event) => { const button = event.target.closest("button[data-id]"); if (button) { const student = students[button.dataset.id]; setPending({ id: button.dataset.id, status: button.dataset.status, student }); } }}>{list.map(([id, student]) => <article className="request-row" key={id}><div><h2>{student.name}</h2><p>{id} · {student.course}</p></div><StatusBadge status={student.clearanceStatus?.[user.office] || "pending"} /><div className="actions"><button className="button approve" data-id={id} data-status="approved">Approve</button><button className="button reject" data-id={id} data-status="rejected">Reject</button></div></article>)}</div></section><aside className="dashboard-side"><section className="card"><h2>Manual student search</h2><label htmlFor="student-search">ID or email</label><input id="student-search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search after 300 ms" />{match === "none" && <p>No student found.</p>}{match && match !== "none" && <div className="match"><strong>{match.name}</strong><p>{match.studentId} · {match.course}</p>{Object.entries(match.clearanceStatus || {}).map(([office, status]) => <p key={office}>{office}: <StatusBadge status={status} /></p>)}</div>}</section><section className="card"><h2>QR scanner</h2><button className="button primary" onClick={() => setScanner(true)}>Scan QR Code</button><button className="button link-button" onClick={() => setScanner(true)}>Or enter code manually</button></section></aside></div>{scanner && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="scan-title"><h2 id="scan-title">Scan QR Code</h2><p>Camera scanning is unavailable here. Paste or enter the token from the QR link.</p><form onSubmit={scanSubmit}><label htmlFor="manual-token">QR token</label><input id="manual-token" autoFocus value={token} onChange={(e) => setToken(e.target.value)} required /><div className="actions"><button type="button" className="button secondary" onClick={() => setScanner(false)}>Close</button><button type="submit" className="button primary">Verify code</button></div></form></section></div>}<ConfirmationModal open={Boolean(pending)} title="Confirm clearance update" message={pending ? `${pending.status === "approved" ? "Approve" : "Reject"} ${pending.student.name}'s ${user.office} clearance?` : ""} onClose={() => setPending(null)} onConfirm={confirm} loading={saving} /><Toast message={toast} /></main>;
>>>>>>> 745318e781b58dce7c117af074a67a6b4c419ef4
}
